### ISSUE TITLE
Make logging configurable

### ISSUE THREAD

**Issue by elsbrock** [zou-yu/worker-mailer#4]
I noticed the library is logging a lot of stuff, including protocol details such as authentication. We should make this configurable or disable it entirely.

**Comment by zou-yu** [comment]
Sorry for the bad experience. Please upgrade this package to `1.0.0`. I just added logLevel as an option, and I forgot to export LogLevel Enum while packaging, so you can't set up logging level for now. But the default log level is INFO, so you won't see this stuff by default...

**Comment by elsbrock** [comment]
Thanks, no worries! It's much better now, the only two messages I see in the logs are:

```
    {
      "message": [
        "[WorkerMailer:example.com:465]Connecting to SMTP server"
      ],
      "level": "info",
      "timestamp": 1731623701565
    },
    {
      "message": [
        "[WorkerMailer:example.com:465]SMTP server connected"
      ],
      "level": "info",
      "timestamp": 1731623701727
    }
```

Is that intended? Cheers!

**Comment by zou-yu** [comment]
#8 Now you can set log level by updating to 1.0.1
